### PR TITLE
Add new Run2.2i DR3

### PR DESCRIPTION
**Pull request by heather999**
Testing that CFS at NERSC can be used in batch, so there is no longer a need to copy the data to CSCRATCH.  Added a new entry for Run2.2i DR3 - and will test this with the desc-stack env.

### CODE REVIEW

**Review by yymao — DISMISSED** [review]
Is there a particular reason that we are jumping to 0.5 rather than 0.4? Looks good to me in any case.

**Comment by heather999** [comment]
We had a 0.4.0 release, I just failed to update version last time.

**Comment by heather999** [comment]
Unfortunately, I was incorrect batch access to CFS does not work.. we still have that locking issue.  So this provided path will only work for interactive sessions.  
I'm working to see what I can pull onto CSCRATCH, but it seems doubtful I will put all 200 TB of calexps on CSCRATCH.  We could have 2 paths defined..  one to the full data set and another to be used for those requiring batch access.

**Comment by heather999** [comment]
Thanks to Jim Chiang, we have a fix in place so we can use the CFS area and manage access from NERSC's compute nodes.  Testing will continue, and once complete, this PR will be merged and closed.

**Comment by heather999** [comment]
@yymao Sorry to bother you - I, likely unwisely, decided to add in the repo for DIA tract 3828 that was discussed on #13 ... that means this PR needs a fresh review.

**Review by yymao — APPROVED** [review]

**Pull request merged**
