### PR TITLE
Prepare of Run2.2i DR2-v1 and DR6-v2 releases

### PR DESCRIPTION
**Pull request by heather999**
Addresses #22 which involves the move to `/global/cfs/cdirs/lsst/shared/DC2-prod`.
updates 2.2i_dr2 and 2.2i_dr6_wfd, also adding 2.2i_dr6 as an alias for 2.2i_dr6_wfd due to our earlier decision that "wfd" doesn't belong in this release identifier.
These directories are in the process of being created on `/global/cfs/cdirs/lsst/shared/DC2-prod`.

### CODE REVIEW

**Comment by heather999** [comment]
@yymao These directories have now been set up at NERSC and I think this is ready to go.  I've also updated the version to v0.9.0

**Review by yymao — COMMENTED** [review]
Loading `2.2i_dr2` I got:
```
PermissionError: [Errno 13] Permission denied: '/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/desc_dm_drp/v19.0.0/rerun/run2.2i-calexp-v1'
```

Loading `2.2i_dr6` I got:

```
RuntimeError: No default mapper could be established from inputs:[] and no mapper specified for outputs:[RepoData(id=46912876647592,repoArgs=RepositoryArgs(root='/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/desc_dm_drp/v19.0.0/rerun/run2.2i-dr6-v2', cfgRoot=None, mapper=None, mapperArgs=None, tags=set(), mode='rw', policy=None)cfg=RepositoryCfg(root='/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/desc_dm_drp/v19.0.0/rerun/run2.2i-dr6-v2', mapper=None, mapperArgs={}, parents=[], policy=None),cfgOrigin=new,cfgRoot=/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/desc_dm_drp/v19.0.0/rerun/run2.2i-dr6-v2,repo=None,parentRepoDatas=[],isV1Repository=False,role=output,parentRegistry=None)]
```

Also, should we keep a `2.2i_dr6_v1` entry?

**Comment by heather999** [comment]
Should be fixed now.  I'll check it in a few minutes..

I think we should keep `2.2i_dr6_v1` for now - people may be using it and that data is still in place.  Ultimately, once dr6-v2 is established, there should be no need for v1, but I'd like to announce its removal before doing so.

**Comment by yymao** [comment]
- `2.2i_dr2_v1` -- now works for me. 
- `2.2i_dr6_v2` -- still get the same `RuntimeError: No default mapper` as of now.
- `2.2i_dr6_v1` -- I agree that we should keep it, but it's not in the current PR right now.

**Comment by yymao** [comment]
Thanks. All the new repos now work for me. 

For CC site, should we create `2.2i_dr6` as well? Also `2.2i_dr6_wfd` is still pointing to v1, is that intended?

**Review by yymao — APPROVED** [review]
NERSC part looks good to me. CC entries may not be consistent with NERSC it seems.

**Comment by heather999** [comment]
Thanks for the testing! 
We should come back and consider what to do with CC, some areas are identical to what we have at NERSC, such as run2.2i_dr2 (at least as of today - unless there is a later call to reprocess something), other areas like the release of run2.2_dr6_v1 and v2 are still active processing areas where the DDF region is still in progress.  What we released as run2.2i DR6 explicitly excludes some tracts & patches that are still available at CC.  We might want to think about how to best name those areas to make it clear what the distinctions are.
So I don't think we want to create a `2.2i_dr6` for CC, because it may be misleading.
I'll check on `2.2i_dr6_wfd` - I guess it should be updated.  I'm hoping we can ultimately drop that name. ah that's also in the context of CC - there is no -v2 there, they only have one processing area that is still named `-v1`, the same processing area is under ongoing use.

**Comment by yymao** [comment]
Good point. So for CC, should we rename `2.2i_dr6_wfd` to `2.2i_dr6_prod`, so that it's clear that it is not the same as `2.2i_dr6_wfd` at NERSC?

**Comment by heather999** [comment]
I'm hesitating about renaming the CC repo names - I'm assuming they are using the existing ones in notebooks.  We could add a `2.2i_dr6_prod` in addition maybe to help with a transition?  This is something we should coordinate with @johannct

**Comment by yymao** [comment]
👍 We can merge this first and deal with CC repos later if that's preferred.

**Comment by johannct** [comment]
we want full mirroring, without any consideration that part or even most of the data lie already somewhere at CC. Timestamp the same, etc... Is that what the problem is right now : that some of the shared area have not been transferred?

**Comment by heather999** [comment]
I am going to proceed to merge and tag this so we can get the DR2 & DR6-v2 releases out.  I"ll point to this and open a separate issue.

We have mirrored - and in the case of Run2.2i DR2 what we have is identical.  The issue is with what we release as DR6-v2 and DR6-v1 - recall that we have excluded those DDF region tracts & patches.  If CC wants to mirror that and you have room for it, that would be great, and we would have at least DR6-v2 at both sites explicitly. 
We also have an area meant to be synced with CC for the ongoing DR6 production that includes the DDF - that area should be brought back up to date (not today :) ) and then I would think we would have "repos" that are named `run2.2i-dr6-prod` at both sites.  It would need to be understood that is distinct from the released data - since data may "change" due to ongoing processing and reprocessing.
But we should do some thinking about how to best handle this.

**Pull request merged**
