### PR TITLE
Prepare a v0.7.0 tag

### PR DESCRIPTION
**Pull request by yymao**
As title

### CODE REVIEW

**Comment by heather999** [comment]
Just want to check on this @johannct: https://github.com/LSSTDESC/desc-dc2-dm-data/blob/6836fb54ec5315f970d934ce5f9fffb79565eec9/desc_dc2_dm_data/repos.py#L40
I'm assuming this is a type and should be: `run2.2i-coadd-wfd-dr2-v1`
Which begs the question.. are we ready to "release" DR2 - do we have object cats or metacal available?  Should I be asking for a copy at NERSC?

**Comment by johannct** [comment]
fixed, thanks @heather999

**Comment by yymao** [comment]
I think this is now ready to be reviewed (and then merged and tagged).

**Review by heather999 — APPROVED** [review]
LGTM

**Pull request merged**
