### PR TITLE
Updating repo path for Run1.2p_v4

### PR DESCRIPTION
**Pull request by heather999**
update repo path for Run1.2p_v4 due to new data received from IN2P3: https://github.com/LSSTDESC/ImageProcessingPipelines/issues/80

### CODE REVIEW

**Review by yymao — CHANGES_REQUESTED** [review]
Do we want to add `1.2p_v3` as well? 

Also, we should change the version of this package by updating `version.py`.

**Review by yymao — DISMISSED** [review]
Minor question: why 0.2.1 rather than 0.2.0?

I'll leave the decision about adding `1.2p_v3` to you.

**Review by yymao — APPROVED** [review]
LGTM. Thanks, @heather999!

**Comment by heather999** [comment]
Sorry @yymao Yes, absolutely right.  I fixed the version and set it to 0.2.0.  I think it's a good idea to provide some way for users to easily reset their repos to some earlier version of the data.  Added new repo entries for Run1.2p_v3 and Run1.2p_v4 as well as setting Run1.2p to the latest dataset.

**Pull request merged**
